version: "3.6"

services:

  service-slayer-arbiter-api:
    build: ./arbiter-api/
    container_name: service-slayer-arbiter-api
    ports:
      - 2999:3000
    environment:
      - CLUSTER_NAME=service-slayer-cluster
      - REGION_NAME=us-east-1

  service-slayer-defense-api:
    build: ./defense-api/
    container_name: service-slayer-defense-api
    ports:
      - 3000:3000

  service-slayer-offense-api:
    build: ./offense-api/
    container_name: service-slayer-offense-api
    ports:
      - 3001:3000

  service-slayer-game-site:
    build: ./game-site/
    container_name: service-slayer-game-site
    ports:
      - 80:80
