version: "3.6"

services:

  sneaky-snake-arbiter-api:
    build: ./arbiter-api/
    container_name: sneaky-snake-arbiter-api
    ports:
      - 2999:2999
    environment:
      - CLUSTER_NAME=sneaky-snake-cluster
      - REGION_NAME=us-east-1

  sneaky-snake-defense-api:
    build: ./defense-api/
    container_name: sneaky-snake-defense-api
    ports:
      - 3000:3000

  sneaky-snake-offense-api:
    build: ./offense-api/
    container_name: sneaky-snake-offense-api
    ports:
      - 3001:3001
